spring:
    application:
        name:
            ecomm-gateway-service
            
    cloud:
        gateway:
            routes:
                - id: ecomm-user-service
                  uri: lb://ecomm-user-service
                  predicates:
                    - Path=/api/users/**
                - id: ecomm-cart-service
                  uri: lb://ecomm-cart-service
                  predicates:
                    - Path=/api/carts/**
                - id: ecomm-product-service
                  uri: lb://ecomm-product-service
                  predicates:
                    - Path=/api/products/**
                - id: ecomm-inventory-service
                  uri: lb://ecomm-inventory-service
                  predicates:
                    - Path=/api/inventory/**
                - id: ecomm-order-service
                  uri: lb://ecomm-order-service
                  predicates:
                    - Path=/api/orders/**               

server:
    port: 8082
    